config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  get "home", to: "home#index"

  root "home#index"

  resources :albums, only: [:index, :show]

  resources :events, only: [:index, :show]

  resources :discounts, only: [:index, :show] do
    resources :coupons, only: [:index, :new, :create]
  end

  scope :my do
    resources :coupons
  end

  namespace :blog do
    get "/", to: "articles#index"

    resources :articles, only: [:index, :show]
      # resources :comments, only: [:create]
  end

  namespace :admin do
    get "/", to: "base#home", as: "home"

    resources :sliders
    resources :articles
    resources :events

    resources :discounts do
      resources :coupons
    end

    resources :albums do
      resources :photos, except: [:edit, :update]
    end

  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to  :album

  has_attached_file :image,
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
  validates :title, :description, :album, :date_init, :date_end, :image,  presence: true
  validates_datetime :date_init, :date_end

  def date_init_value
    date_init.strftime('%d/%m/%Y a las %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y a las %H:%M')
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  expose(:albums) { Album.all }

  respond_to :html

  private

  def event_params
    params.require(:event).permit(:title, :description, :album_id, :image, :date_init, :date_end)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  respond_to :html

  expose(:events){ Event.all }
  expose(:event) { Event.find(params[:id]) }

  def index; end
  def show; end

end

app/views/admin/events/_form.slim
= form_for([:admin, resource], html: { class: 'form' }) do |f|
  - if resource.errors.any?
   #error_explanation
      h2
        = pluralize(resource.errors.count, "error")
        |prohibited this admin_album from being saved:
      ul
        - resource.errors.full_messages.each do |message|
          li
            = message
  .fields
    .field
      = f.label :title, 'Título'
      = f.text_field :title
    .field
      = f.label :description, 'Descripción'
      = f.text_field :description
    .field
      = f.label :date_init, 'Fecha de inicio'
      = f.datetime_local_field :date_init
    .field
      = f.label :date_end, 'Fecha de fin'
      = f.datetime_local_field :date_end
    .field
      = f.label :image, 'Imagen'
      = f.file_field :image
    .field
      = f.label :album_id, 'Álbum'
      = f.select(:album_id, albums.collect {|album| [ album.name, album.id ] }, { include_blank: 'Seleccionar album' })

  .actions
    .action
      = f.submit

app/views/admin/events/edit.html.slim
h1.title-section
  span Editar evento
  = link_to 'Volver', admin_events_path, class: 'btn green action'

= render 'form'

app/views/admin/events/index.html.slim
h1.title-section
  span Lista de eventos
  = link_to 'Nuevo evento', new_admin_event_path, class: 'btn green action'

table.table
  thead
    tr
      th #
      th Imagen
      th Título
      th Descripción
      th Fecha de inicio
      th Fecha de fin
      th Album
      th colspan="4" Acciones

  tbody
    - collection.each do |event|
      tr
        td = event.id
        td = image_tag event.image.url(:thumb)
        td = event.title
        td = event.description
        td = event.date_init_value
        td = event.date_end_value
        td = event.album.name if event.album
        td = link_to 'Ver fotos',admin_album_photos_path(event), class: 'btn small blue'
        td = link_to 'Ver evento', [:admin, event], class: 'btn small green'
        td = link_to 'Edit', edit_admin_event_path(event), class: 'btn small orange'
        td = link_to 'Destroy', [:admin, event], method: :delete, data: { confirm: 'Estás seguro' }, class: 'btn small red'

app/views/admin/events/new.html.slim
h1.title-section
  span Nuevo evento
  = link_to 'Volver', admin_events_path, class: 'btn green action'

= render 'form'

app/views/admin/events/show.html.slim
h1.title-section
  span = resource.title
  .actions
    = link_to 'Volver', admin_events_path, class: 'btn green action'
    = link_to 'Editar', edit_admin_event_path(resource), class: 'btn orange action'
    = link_to 'Eliminar', admin_event_path(resource), method: :delete, data: { confirm: 'Estás seguro?' }, class: 'btn green red action'

.show-item
  .row
    strong Descripción:&nbsp;
    = resource.description
  .row
    strong Álbum:&nbsp;
    - if resource.album
      = resource.album.name
    - else
      |No se ha seleccionado un álbum