config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  get "home", to: "home#index"

  root "home#index"

  resources :albums, only: [:index, :show]

  resources :events, only: [:index, :show]

  resources :discounts, only: [:index, :show] do
    resources :coupons, only: [:index, :new, :create]
  end

  scope :my do
    resources :coupons
  end

  namespace :blog do
    get "/", to: "articles#index"

    resources :articles, only: [:index, :show]
      # resources :comments, only: [:create]
  end

  namespace :admin do
    get "/", to: "base#home", as: "home"

    resources :sliders
    resources :articles
    resources :events

    resources :discounts do
      resources :coupons
    end

    resources :albums do
      resources :photos, except: [:edit, :update]
    end

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many  :photos
  has_many  :events
  validates :name, :description, presence: true
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId

  has_many :comments

  friendly_id :title, use: :slugged

  validates :title, :description, :content, presence: true

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  belongs_to  :discount
  belongs_to  :user

  before_create :generate_code
  after_save :subtracting_stock

  validates :discount, :user, presence: true

  def subtracting_stock
    discount.update_attribute(:count, discount.count - 1)
  end

  def generate_code(size = 6)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    #Loop for create code random unique, if code exists in DB, regenerate code in loop
    begin
      codecoupon = (0...size).map{ charset.to_a[rand(charset.size)] }.join
    end while(Coupon.where(code: codecoupon).count > 0)

    self.code = codecoupon
  end
  
end

app/models/discount.rb
class Discount < ActiveRecord::Base

  has_many  :coupons

  has_attached_file :image, 
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, 
                                    content_type: /\Aimage\/.*\Z/
  
  validates :title, :description, :count, :date_ini, :date_end, :percent, :image,  presence: true
  validates_datetime :date_ini, :date_end

  scope :actives, -> { where("date_end > '#{Time.now - 2.days}'").order(date_end: :desc) }

  def date_ini_value
    date_ini.strftime('%d/%m/%Y %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y %H:%M')
  end

  def expired?
    date_end < Time.now
  end
    
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to  :album

  has_attached_file :image,
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
  validates :title, :description, :album, :date_init, :date_end, :image,  presence: true
  validates_datetime :date_init, :date_end

  def date_init_value
    date_init.strftime('%d/%m/%Y a las %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y a las %H:%M')
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image, 
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, 
                                    content_type: /\Aimage\/.*\Z/
  validates :image, :album, presence: true

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image,
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :coupons

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  private

    def album_params
      params.require(:album).permit(:name, :description)
    end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  defaults resource_class: Article.friendly

  private

    def article_params
      params.require(:article).permit(:title, :description, :content)
    end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < InheritedResources::Base
  before_action :authenticate_admin!

  layout 'admin'

  def home; end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  expose(:albums) { Album.all }

  respond_to :html

  private

  def event_params
    params.require(:event).permit(:title, :description, :album_id, :image, :date_init, :date_end)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  expose(:albums) { Album.all }
  expose(:photos) { Album.find(params[:id]).photos }
  
  def index; end
  def show; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  expose(:article) { Article.friendly.find(params[:id]) }
  expose(:articles){ Article.paginate(:page => params[:page], :per_page => 9).all }
  expose(:comment) { Comment.new }
  expose(:comments){ Comment.all }

  def index; end
  def show; end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:article)    { Article.find(params[:article_id]) }

  def create
    c = article.comments.build(comment_params)

    if c.save
      redirect_to article_path(article), notice: 'Se ha creado el comentario correctamente'
    else
      # render :show
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:article_id, :body)
  end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController

  before_action :authenticate_user!

  expose(:discount) { Discount.find(params[:discount_id])  }
  expose(:coupons){ current_user.coupons }
  expose(:coupon) { coupons.find(params[:id]) }

  respond_to :html

  def create
    if discount.expired?
      return redirect_to(:back, notice: 'Descuento expirado')
    end

    if current_user.coupons.where(discount: discount).size > 1
      return redirect_to(:back, notice: 'Solo puedes obtener 2 cupones de un mismo descuento')
    end

    cup = current_user.coupons.create(discount: discount)
    redirect_to coupon_path(cup), notice: "Genial!!! Tu cupon ha sido creado."
  end

end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController

  expose(:discounts){ Discount.actives }
  expose(:discount) { Discount.find(params[:id]) }

  def index; end
  def show; end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  respond_to :html

  expose(:events){ Event.all }
  expose(:event) { Event.find(params[:id]) }

  def index; end
  def show; end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:sliders)  { Slider.all }
  expose(:events)   { Event.all.limit(3) }
  expose(:discounts){ Discount.all.limit(2) }
  expose(:articles) { Article.all.limit(3) }

  layout 'home'

  def index;   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.slim
= form_for([:admin, resource], html: { class: 'form' }) do |f|
  - if resource.errors.any?
   #error_explanation
      h2
        = pluralize(resource.errors.count, "error")
        |prohibited this admin_album from being saved:
      ul
        - resource.errors.full_messages.each do |message|
          li
            = message

  .fields
    .field
      = f.label :title, 'Título'
      = f.text_field :title
    .field
      = f.label :description, 'Descripción'
      = f.text_area :description
    .field
      = f.label :content, 'Contenido'
      = f.text_area :content

  .actions
    .action
      = f.submit

app/views/admin/articles/edit.html.slim
h1.title-section
  span Editar artículo
  = link_to 'Volver', admin_articles_path, class: 'btn green action'

= render 'form'

app/views/admin/articles/index.html.slim
h1.title-section
  span Lista de artículos
  = link_to 'Nuevo artículo', new_admin_article_path, class: 'btn green action'

table.table
  thead
    tr
      th #
      th Titulo
      th Descripción
      th Contenido
      th colspan="3" Acciones

  tbody
    - collection.each do |article|
      tr
        td = article.id
        td = article.title
        td = article.description
        td = article.content
        td = link_to 'Ver', admin_article_path(article.id), class: 'btn small green'
        td = link_to 'Editar', edit_admin_article_path(article), class: 'btn small orange'
        td = link_to 'Eliminar', admin_article_path(article), method: :delete, data: { confirm: 'Estás seguro?' }, class: 'btn small red'

app/views/admin/articles/new.html.slim
h1.title-section
  span Nuevo artículo
  = link_to 'Volver', admin_articles_path, class: 'btn green action'

= render 'form'

app/views/admin/articles/show.html.slim
h1.title-section
  span = resource.title
  .actions
    = link_to 'Volver', admin_articles_path, class: 'btn green action'
    = link_to 'Editar', edit_admin_article_path(resource), class: 'btn orange action'
    = link_to 'Eliminar', admin_article_path(resource), method: :delete, data: { confirm: 'Estás seguro?' }, class: 'btn green red action'

.show-item
  .row
    strong Descripción:&nbsp;
    = resource.description
  .row
    strong Contenido:&nbsp;
    = resource.content