config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  get "home", to: "home#index"

  root "home#index"

  resources :albums, only: [:index, :show]

  resources :events, only: [:index, :show]

  resources :discounts, only: [:index, :show] do
    resources :coupons, only: [:index, :new, :create]
  end

  scope :my do
    resources :coupons
  end

  namespace :blog do
    get "/", to: "articles#index"

    resources :articles, only: [:index, :show]
      # resources :comments, only: [:create]
  end

  namespace :admin do
    get "/", to: "base#home", as: "home"

    resources :sliders
    resources :articles
    resources :events

    resources :discounts do
      resources :coupons
    end

    resources :albums do
      resources :photos, except: [:edit, :update]
    end

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many  :photos
  has_many  :events
  validates :name, :description, presence: true
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId

  has_many :comments

  friendly_id :title, use: :slugged

  validates :title, :description, :content, presence: true

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  belongs_to  :discount
  belongs_to  :user

  before_create :generate_code
  after_save :subtracting_stock

  validates :discount, :user, presence: true

  def subtracting_stock
    discount.update_attribute(:count, discount.count - 1)
  end

  def generate_code(size = 6)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    #Loop for create code random unique, if code exists in DB, regenerate code in loop
    begin
      codecoupon = (0...size).map{ charset.to_a[rand(charset.size)] }.join
    end while(Coupon.where(code: codecoupon).count > 0)

    self.code = codecoupon
  end
  
end

app/models/discount.rb
class Discount < ActiveRecord::Base

  has_many  :coupons

  has_attached_file :image, 
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, 
                                    content_type: /\Aimage\/.*\Z/
  
  validates :title, :description, :count, :date_ini, :date_end, :percent, :image,  presence: true
  validates_datetime :date_ini, :date_end

  scope :actives, -> { where("date_end > '#{Time.now - 2.days}'").order(date_end: :desc) }

  def date_ini_value
    date_ini.strftime('%d/%m/%Y %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y %H:%M')
  end

  def expired?
    date_end < Time.now
  end
    
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to  :album

  has_attached_file :image,
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
  validates :title, :description, :album, :date_init, :date_end, :image,  presence: true
  validates_datetime :date_init, :date_end

  def date_init_value
    date_init.strftime('%d/%m/%Y a las %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y a las %H:%M')
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image, 
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, 
                                    content_type: /\Aimage\/.*\Z/
  validates :image, :album, presence: true

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image,
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :coupons

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  private

    def album_params
      params.require(:album).permit(:name, :description)
    end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < InheritedResources::Base
  before_action :authenticate_admin!

  layout 'admin'

  def home; end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  expose(:albums) { Album.all }

  respond_to :html

  private

  def event_params
    params.require(:event).permit(:title, :description, :album_id, :image, :date_init, :date_end)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  expose(:albums) { Album.all }
  expose(:photos) { Album.find(params[:id]).photos }
  
  def index; end
  def show; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:article)    { Article.find(params[:article_id]) }

  def create
    c = article.comments.build(comment_params)

    if c.save
      redirect_to article_path(article), notice: 'Se ha creado el comentario correctamente'
    else
      # render :show
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:article_id, :body)
  end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController

  before_action :authenticate_user!

  expose(:discount) { Discount.find(params[:discount_id])  }
  expose(:coupons){ current_user.coupons }
  expose(:coupon) { coupons.find(params[:id]) }

  respond_to :html

  def create
    if discount.expired?
      return redirect_to(:back, notice: 'Descuento expirado')
    end

    if current_user.coupons.where(discount: discount).size > 1
      return redirect_to(:back, notice: 'Solo puedes obtener 2 cupones de un mismo descuento')
    end

    cup = current_user.coupons.create(discount: discount)
    redirect_to coupon_path(cup), notice: "Genial!!! Tu cupon ha sido creado."
  end

end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController

  expose(:discounts){ Discount.actives }
  expose(:discount) { Discount.find(params[:id]) }

  def index; end
  def show; end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  respond_to :html

  expose(:events){ Event.all }
  expose(:event) { Event.find(params[:id]) }

  def index; end
  def show; end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:sliders)  { Slider.all }
  expose(:events)   { Event.all.limit(3) }
  expose(:discounts){ Discount.all.limit(2) }
  expose(:articles) { Article.all.limit(3) }

  layout 'home'

  def index;   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/base/home.slim
|Bienvenido admin

= link_to 'Ver albumes',admin_albums_path

app/views/base/home.html.erb
<h1>Bienvenido user</h1>

app/views/home/index.html.slim
.full-background
  i.icon-down

h1
  span Los mejores eventos para tu fin de semana están en:
  = image_tag('logo.png', alt: "Titanium")

= render 'shared/application/header'

.slider
  .swiper-container
    .swiper-wrapper
      - sliders.each do |slider|
        .swiper-slide
          = image_tag slider.image.url(:original)

/ Events
section
  .inner-container
    = link_to events_path, class: 'link-to-section' do
      h2 Eventos
      i.icon-next

    .items
      - events.each do |event|
        = link_to event_path(event), class: 'item' do

          .item-image
            = image_tag event.image.url(:original)

          .item-content
            .item-title
              = event.title
            .item-description
              = event.description
            .item-date
              span Inicia:&nbsp;
              strong = event.date_init_value
              br
              span Finaliza&nbsp;
              strong = event.date_end_value

    .wrapper-btn
      = link_to 'Ver todos', events_path, class: 'btn pink'

/ Discounts
section
  .inner-container
    = link_to discounts_path, class: 'link-to-section' do
      h2 Descuentos
      i.icon-next

    .items.discounts
      - discounts.each do |discount|

        .discount
          = link_to discount_path(discount), class: 'item' do

            .item-discount
              = discount.percent.to_i
              |%
            .item-image
              = image_tag discount.image.url(:original)
            .item-content
              .item-date
                span Finaliza&nbsp;
                strong = discount.date_end

          .content
            .item-title
              = discount.title
            .item-description
              = discount.description
            .item-description.item-share
              span Compartir descuento:
              ul
                li
                  a href="#"
                    i.icon-facebook
                  a href="#"
                    i.icon-twitter
                  a href="#"
                    i.icon-linkedin


    .wrapper-btn
      = link_to 'Ver todos', discounts_path, class: 'btn pink'

/ Blog
section
  .inner-container
    = link_to blog_articles_path, class: 'link-to-section' do
      h2 Blog
      i.icon-next

    .items.articles
      - articles.each do |article|
        = link_to blog_article_path(article), class: 'item' do

          .item-image
            /= image_tag article.image.url(:original)

          .item-content
            .item-title
              = article.title
            .item-description
              = article.description

    .wrapper-btn
      = link_to 'Ver blog', blog_articles_path, class: 'btn pink'
/ .title
/  - 10000.times do
/     |Lorem