config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  get "home", to: "home#index"

  root "home#index"

  resources :albums, only: [:index, :show]

  resources :events, only: [:index, :show]

  resources :discounts, only: [:index, :show] do
    resources :coupons, only: [:index, :new, :create]
  end

  scope :my do
    resources :coupons
  end

  namespace :blog do
    get "/", to: "articles#index"

    resources :articles, only: [:index, :show]
      # resources :comments, only: [:create]
  end

  namespace :admin do
    get "/", to: "base#home", as: "home"

    resources :sliders
    resources :articles
    resources :events

    resources :discounts do
      resources :coupons
    end

    resources :albums do
      resources :photos, except: [:edit, :update]
    end

  end

end

app/models/discount.rb
class Discount < ActiveRecord::Base

  has_many  :coupons

  has_attached_file :image, 
                    styles: {
                        thumb: "70x70"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, 
                                    content_type: /\Aimage\/.*\Z/
  
  validates :title, :description, :count, :date_ini, :date_end, :percent, :image,  presence: true
  validates_datetime :date_ini, :date_end

  scope :actives, -> { where("date_end > '#{Time.now - 2.days}'").order(date_end: :desc) }

  def date_ini_value
    date_ini.strftime('%d/%m/%Y %H:%M')
  end

  def date_end_value
    date_end.strftime('%d/%m/%Y %H:%M')
  end

  def expired?
    date_end < Time.now
  end
    
end

app/controllers/admin/discounts_controller.rb
class Admin::DiscountsController < Admin::BaseController
  respond_to :html

  private

  def discount_params
    params.require(:discount).permit(:title, :description, :count, :image, :date_ini, :date_end, :percent)
  end
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController

  expose(:discounts){ Discount.actives }
  expose(:discount) { Discount.find(params[:id]) }

  def index; end
  def show; end

end

app/views/discounts/index.html.erb
<h1>Listing Discounts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Count</th>
      <th>Image</th>
      <th>Fecha de inicio</th>
      <th>Fecha de fin</th>
      <th>Percent</th>
      <th>Expired</th>

      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% discounts.each do |discount| %>
      <tr>
        <td><%= discount.title %></td>
        <td><%= discount.description %></td>
        <td><%= discount.count %></td>
        <td><%= image_tag discount.image.url(:thumb) %></td>
        <td><%= discount.date_ini_value %></td>
        <td><%= discount.date_end_value %></td>
        <td><%= discount.percent %></td>
        <td><%= discount.expired? ? 'SI' : 'NO' %></td>
        <td><%= link_to 'Show', [discount] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= discount.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= discount.description %>
</p>

<p>
  <strong>Count:</strong>
  <%= discount.count %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag discount.image.url(:thumb) %>
</p>

<p>
  <strong>Date init:</strong>
  <%= discount.date_ini_value %>
</p>

<p>
  <strong>Date end:</strong>
  <%= discount.date_end_value %>
</p>

<p>
  <strong>Percent:</strong>
  <%= discount.percent %>
</p>


<%= link_to 'get coupon', new_discount_coupon_path(discount) %>
<%= link_to 'Back', discounts_path %>